/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface GreetingDto
 */
export interface GreetingDto {
    /**
     * 
     * @type {string}
     * @memberof GreetingDto
     */
    'message': string;
}

/**
 * GreetingsApi - axios parameter creator
 * @export
 */
export const GreetingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGreeting: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/greetings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GreetingsApi - functional programming interface
 * @export
 */
export const GreetingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GreetingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGreeting(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GreetingDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGreeting(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GreetingsApi - factory interface
 * @export
 */
export const GreetingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GreetingsApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGreeting(options?: any): AxiosPromise<GreetingDto> {
            return localVarFp.getGreeting(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GreetingsApi - interface
 * @export
 * @interface GreetingsApi
 */
export interface GreetingsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GreetingsApiInterface
     */
    getGreeting(options?: AxiosRequestConfig): AxiosPromise<GreetingDto>;

}

/**
 * GreetingsApi - object-oriented interface
 * @export
 * @class GreetingsApi
 * @extends {BaseAPI}
 */
export class GreetingsApi extends BaseAPI implements GreetingsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GreetingsApi
     */
    public getGreeting(options?: AxiosRequestConfig) {
        return GreetingsApiFp(this.configuration).getGreeting(options).then((request) => request(this.axios, this.basePath));
    }
}


