issuer: https://dev-ch4mpy.eu.auth0.com/
allowed-origins:
- http://localhost:3002
- http://localhost:3003
- https://localhost:3402
- https://localhost:3403

server:
  port: 8080
  error:
    include-message: always
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s

com:
  c4-soft:
    springaddons:
      security:
        cors:
        - path: /greetings/**
          allowed-origins: ${allowed-origins}
        issuers:
        - location: ${issuer}
          username-claim: $['https://c4-soft.com/user']['name']
          authorities:
          - path: $['https://c4-soft.com/user']['roles']
          - path: $.permissions
        permit-all:
        - "/greetings/**"
        - "/actuator/health/readiness"
        - "/actuator/health/liveness"
        - "/v3/api-docs/**"
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

---
server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl